### ISSUE TITLE
Thinking about staying closer to vanilla HTML

### ISSUE THREAD

**Issue by amotl** [almonk/pylon#3]
Dear Alasdair,

### Introduction
We just came across this [1] on HN [2] and want to tell you that the idea of
> [...] **encapsulating Flexbox logic into a set of declarative and expressive tags and attributes which, when combined, form robust user interfaces**. 

resonates very well with us. We are still unsure if that could likewise be implemented through [WebComponents](https://www.webcomponents.org/) and friends, but that's a another story.

Nevertheless, we would like to humbly share our thoughts by citing [_manifestsilence_](https://news.ycombinator.com/user?id=manifestsilence) here.

### Thoughts
> Very cool, but I'd like to  point out that unless/until this gets very popular to where Google  changes their practices, it wrecks certain SEO perks (though so do a lot  of fancy practices). Google still really likes plain old HTML  primitives like `<OL>` or `<UL>` for lists, `<TABLE>` for  tables, `<P>` for paragraph. Their featured snippets appear to be  capable of extracting info that isn't in that form and bumping it to the  top of results, but to prefer not to. My $.02 from starting to learn  that game.
>
> -- https://news.ycombinator.com/item?id=20156752

It's not that we are as concerned about SEO things like _manifestsilence_ here, we just would like to ask whether the design of your concept could well be shifted towards a more CSS-only approach by not introducing new HTML tags on the **layout primitive level** already (that might be intended for larger WebComponents maybe?), but by staying more closely to the regular thing of annotating vanilla HTML tags with CSS classes.

### By example
To reflect that by the means of an example, we took that guy from your splash.

#### Your proposal
```html
<list>
  <hstack spacing=s>
    <div class="icon"></div>
    <text>Westminster</text>
    <spacer></spacer>
    <text>0.5 miles</text>
  </hstack>
  ...
```

#### Our idea
```html
<div class="list">
  <span class="hstack" spacing=s>
    <div class="icon"></div>
    <p class="text">Westminster</p>
    <span class="spacer"></span>
    <p class="text">0.5 miles</p>
  </span>
  ...
```

We do see that the latter is more verbose than your proposal. However, it might blend into the contemporary HTML/CSS runtime stack slightly better.

With kind regards,
Andreas.

[1] https://almonk.github.io/pylon/
[2] https://news.ycombinator.com/item?id=20155098

**Comment by almonk** [comment]
@amotl thank you for your thoughtful input. One of my (few) frustrations with atomic CSS is that the markup is not particularly 'obvious'. Which element should I be using and when? The `spacer` in your example, could easily be a `<div>`, or even a plain `<hr/>`. One of the advantages of Pylon is that it's very opinionated about these tags so that developers don't have to think too much about markup. SEO is not a thing I'm super concerned about as the target use case for Pylon is really app interfaces which generally are not optimised for SEO at all anyway.

I understand that the approach definitely isn't for everyone and there are valid accessibility concerns which I'll be addressing in due course, but at the moment I feel like expanding Pylon to work in the way described would make it more confusing for end users.

For now I'm going to close this issue but I will give it thought going forward.

**Comment by amotl** [comment]
Thanks for listening and good luck!

Just trying to remember the phrase which came to mind when seeing the currently proposed syntax firsthand... Ah!

It a kind of feels like a [Microformat](http://microformats.org/) for doing layout with the right intentions -- would that explanation fit your intentions with it?

**Comment by dym-sh** [comment]
so why `<div class="icon"></div>` instead of `<icon />` or even `<img>`
